# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 13, 9, 58, 0, 188598, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
